### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by DvonHolten** [elffersj/roundingsat#5]
folks,
i have two problem-encodings: the small one can be solved by roundingsat in a time somewhat comparable to that of cadical - around 60 seconds or so.
the larger one is solved by cadical in 3300 seconds, and roundingsat is chewing on it since more than 12 hours. 
the difference between the 'small' and the 'large' problem is the number and size of cardinality-constraints.
interested? maybe you want to have a look at your parameters ?
[Puzzle19Jul10x10C15p1v3-1756.zip](https://github.com/elffersj/roundingsat/files/3416907/Puzzle19Jul10x10C15p1v3-1756.zip)
[Puzzle19Jul12x12C16H5p1v3-1756.zip](https://github.com/elffersj/roundingsat/files/3416908/Puzzle19Jul12x12C16H5p1v3-1756.zip)

**Comment by JoD** [comment]
Hey DvonHolten

You talk about cardinality constraints, but provide a cnf (which only contains clauses). RoundingSat works best when directly giving it the original cardinality constraints instead (via the .opb input format, see http://www.cril.univ-artois.fr/PB16/format.pdf) of their clausal encoding, as it can be hard to recover these constraints.

Can I ask what problem you are trying to solve?

Kind regards - Jo

**Comment by DvonHolten** [comment]
Hey Jo,

 

hmm - i thought your solver is a smart one and can figure out the constraints itself.

ok, no problem. It is clear for me, that some other kind of encoding (for cardinality constraints) is easier für the solver.

But does that apply to the boolean part of the formular as well? 

The problem contains a few thousand (mostly) binary blocking clauses. Then there are a few hundred clauses, which detect some patterns (features).

And then there are a between 100 and 200 cardinality constraints of the form  1-of-150, 2-of-150, …. 6-of-150 over these 'features'.

The plain logic is the easy part, the large number of cardinality-constraints over a larger number of variables is the difficult part.

Naive encoding of the cardinality constraints results in very large formulas, which even plingeling cannot solve in a reasonable time.

Last summer i explored the applicability of Z3 (in SMTLIB) on problems like this (many cardinality-constraints, some addDifferent, lots of boolean logic) and i wasn't too much excited about the results.

Integer things are fine, boolean things are fine - the mix of both is not so good. So i look around in the research papers for a state-of-the-art cardinality-aware SAT-solver.

The problems are the warm-up phase to attack the Eternity2-puzzle. 

greetings

DvH

 

 

Von: Jo Devriendt [mailto:notifications@github.com] 
Gesendet: Montag, 22. Juli 2019 15:05
An: elffersj/roundingsat <roundingsat@noreply.github.com>
Cc: DvonHolten <info@dvholten.de>; Author <author@noreply.github.com>
Betreff: Re: [elffersj/roundingsat] Performance? (#5)

 

Hey DvonHolten

You talk about cardinality constraints, but provide a cnf (which only contains clauses). RoundingSat works best when directly giving it the original cardinality constraints instead (via the .opb input format, see http://www.cril.univ-artois.fr/PB16/format.pdf) of their clausal encoding, as it can be hard to recover these constraints.

Can I ask what problem you are trying to solve?

Kind regards - Jo

**Comment by JoD** [comment]
Hey DvH

Firstly, @elffersj has an experimental branch where indeed cardinality is detected, though I don't know if it can detect a "75-of-150" constraint.

In OPB, encoding cardinality is really straightforward, e.g., "exactly 3-of-6" would simply be `x1+x2+x3+x4+x5+x6 = 3`. "At least 2-of-4" would be `x1+x2+x3+x4 >= 2`. And each at most constraint is simply a conversion of an at least constraint. Note that a cardinality over a negative literal `x'` can be replaced by the identity `x'=1-x`. And finally, each clause is just an "at least 1" cardinality. E.g., the clause `x1 or x2' or x3` would become `x1+x2'+x3 >= 1`, or (after replacing `x2'` by `1-x2`), `x1-x2+x3 >= 0`.

It looks like cardinality is important in your problem, so do try the OPB format which allows natural cardinality encoding (which is best for PB sovlers). And encode the logical constraints as clauses, like you are used to.

It's been a while since I looked at the eternity puzzle, but I'd gladly help you out if you get stuck on the encoding.

**Comment by elffersj** [comment]
Hi DvH,

My solver can detect at-most-1 constraints (but not the master branch) and I have some experimental work on detecting at-most-k constraints for small k (think of it as k<=5). But not very weak ones like >=5-of-150.

Roundingsat could only run faster than Cadical if given a formula in OPB format using the natural encoding of the cardinality constraints. This is explained [here](https://github.com/elffersj/roundingsat/blob/master/InputFormats.md).

**Comment by DvonHolten** [comment]
Hi Jo,

 

thanks for feedback.

I am now in process of changing the output-formatter of my problem-generator.

Have done SMTLIB - so OPB should not be a big problem.

Maybe end-of-week i have some results.

Finding small k would be quite helpful, k <= 5 is sufficient. Larger k's can be formulated with bitCounter-expressions.

Here are some numbers for E2:

47 constraints of type 1-of-196

64 constraints of type 2-of-196

73 constraints of type 3-of-196

48 constraints of type 4-of-196

28 constraints of type 5-of-196

  5 constraints of type 6-of-196

420 constraints of type 1-of-17

 

Thats a lot of stuff, the good thing is: it's bounded. its no longer a big grey blob of unknown size.

We will see.

 

greetings from sunny Hamburg

DvH

Von: elffersj [mailto:notifications@github.com] 
Gesendet: Montag, 22. Juli 2019 23:02
An: elffersj/roundingsat <roundingsat@noreply.github.com>
Cc: DvonHolten <info@dvholten.de>; Author <author@noreply.github.com>
Betreff: Re: [elffersj/roundingsat] Performance? (#5)

 

Hi DvH,

My solver can detect at-most-1 constraints (but not the master branch) and I have some experimental work on detecting at-most-k constraints for small k (think of it as k<=5). But not very weak ones like >=5-of-150.

Roundingsat could only run faster than Cadical if given a formula in OPB format using the natural encoding of the cardinality constraints. This is explained here <https://github.com/elffersj/roundingsat/blob/master/InputFormats.md> .

**Comment by JoD** [comment]
Hey DvH

Thanks for the information! 

I've now had a quick look at the eternity puzzle, and apart from some functionality constraints ("at least one" and "at most one" cardinalities), I do not see how, e.g., a "5-of-196" constraint arises.

So I'm still left wondering: do you (a) require the cardinality constraints to be detected from the input formula, or do you know them already and just want to (b) pass them to the solver in a convenient encoding?

So if (a) cardinality detection is really what you need, then use the experimental version of RoundingSat (https://github.com/elffersj/roundingsat/tree/cardinality_detection, usage info to be obtained from @elffersj). If (b) convenient encoding is what you need, then the default master branch should be fine.

Good luck! - Jo

**Comment by DvonHolten** [comment]
Hi Jo,

 

well, the working title of a description of my encoding would be something like 'edge-matching puzzles as a feature cardinality constraint problem'.

i work only on the inner square, that is 14x14 = 196.

The 'features' are color-patterns of  grid-lines, for example a green-red-corner is feature #55, a black-yellow corner is feature #66. 

We have (for example) 3 green-red corner on the tiles, so we have cardinality-constraint #55 is 3-of-196.

We have (for example) 5 black-yellow corners, so we have card-constraint #66 is 5-in-196.

The 196 variables for each feature sit on the inner grid-cells, their meaning is 'on this cell there exists a green-red corner', 196 vars for feature #55, 196 other vars for feature #66.

The idea with cardinality-detection is, that a huge number of clauses are needed to enforce a 3-of-196 constraint. A SAT-solver can do it, no doubt, but IMO  it is not the

most efficient way. How many conflicts must be handled and how many clauses are learnt (and forgotten) when a 196-variables set changes from { 23, 55, 123 } to { 11, 166, 188} ?

So, (b) is the requirement.

Earlier, i encoded 1-of-n and 2-of-n constraints using some simple encoding, and doing the larger k-values with a bitCounter, That is, i  have bitCounters of width 196, count the true-bits and

force the result to be a constant. These large bitCounters require lots and lots of adders and helper-variables.

 

greetings from Hamburg

DvH

 

 

Von: Jo Devriendt [mailto:notifications@github.com] 
Gesendet: Dienstag, 23. Juli 2019 15:43
An: elffersj/roundingsat <roundingsat@noreply.github.com>
Cc: DvonHolten <info@dvholten.de>; Author <author@noreply.github.com>
Betreff: Re: [elffersj/roundingsat] Performance? (#5)

 

Hey DvH

Thanks for the information!

I've now had a quick look at the eternity puzzle, and apart from some functionality constraints ("at least one" and "at most one" cardinalities), I do not see how, e.g., a "5-of-196" constraint arises.

So I'm still left wondering: do you (a) require the cardinality constraints to be detected from the input formula, or do you know them already and just want to (b) pass them to the solver in a convenient encoding?

So if (a) cardinality detection is really what you need, then use the experimental version of RoundingSat (https://github.com/elffersj/roundingsat/tree/cardinality_detection, usage info to be obtained from @elffersj <https://github.com/elffersj> ). If (b) convenient encoding is what you need, then the default master branch should be fine.

Good luck! - Jo

**Comment by elffersj** [comment]
Hi DvH,

Do you remember how exactly you encoded the constraints with adders? I am writing a tool detecting cardinality constraints encoded as adder networks, but on your CNF formula it only finds half adders (adders with 2 inputs instead of 3).
